#!/bin/bash
#
# Praks 6 yl3 Kevin Tropin
osch=0
echo -n "Sisesta OS1: "
read os
echo -n "Sisesta OS2: "
read oss
echo "1. $os"
echo "2. $oss"
echo -n "Select your os choice [1 or 2]? "
read osch
if [ $osch -eq 1 ] ; then
	echo "You pick up $os"
else #### nested if i.e. if within if #####
	if [ $osch -eq 2 ] ; then
		echo "You pick uo $oss"
	else
		echo "What you dont like Unix/Linux OS."
	fi
fi
#
# Skripti lõpetamine
